export const categoryOptions = [
  { value: "1", label: "Electrónica" },
  { value: "2", label: "Accesorios personales" },
  { value: "3", label: "Documentos" },
  { value: "4", label: "Ropa y calzado" },
  { value: "5", label: "Bolsos y mochilas" },
  { value: "6", label: "Llaves y tarjetas" },
  { value: "7", label: "Libros y papelería" },
  { value: "8", label: "Artículos deportivos" },
  { value: "9", label: "Juguetes y entretenimiento" },
  { value: "10", label: "Salud y cuidado personal" },
  { value: "11", label: "Otros" },
];

export const locationOptionsValue = [
  { value: "1", label: "101 - Torre de Enfermería" },
  { value: "2", label: "102 - Biblioteca Central Gabriel García Márquez (Central)" },
  { value: "3", label: "103 - Centro Polideportivo" },
  { value: "4", label: "104 - Auditorio León de Greffi" },
  { value: "5", label: "201 - Derecho" },
  { value: "6", label: "205 - Sociología (Ciencias Humanas)" },
  { value: "7", label: "207 - Museo de Arquitectura Leopoldo Rother" },
  { value: "8", label: "210 - Odontología" },
  { value: "9", label: "212 - Aulas de Ciencias Humanas" },
  { value: "10", label: "214 - Antonio Narino" },
  { value: "11", label: "217 - Diseño Gráfico" },
  { value: "12", label: "224 - Edificio Manuel Ancizar" },
  { value: "13", label: "225 - Posgrados de Ciencias Humanas" },
  { value: "14", label: "228 - Nuevo Edificio de Enfermería" },
  { value: "15", label: "229 - Lenguas Extranjeras" },
  { value: "16", label: "238 - Contaduria" },
  { value: "17", label: "239 - Filosofía" },
  { value: "18", label: "251 - Capilla" },

  { value: "19", label: "301 - Bellas Artes" },
  { value: "20", label: "305 - Conservatorio de Música" },
  { value: "21", label: "309 - Talleres y aulas de construcción" },
  { value: "22", label: "310 - Facultad de Ciencias Económicas" },
  { value: "23", label: "311 - Facultad de Ciencias Económicas Bloque II" },
  { value: "24", label: "314 - SINDU" },
  { value: "25", label: "317 - Museo de Arte" },
  { value: "26", label: "401 - Ingeniería Julio Garavito (El viejo)" }, // Corregido
  { value: "27", label: "404 - Matemáticas y Física Y/o Takeuchi" },
  { value: "28", label: "405 - Posgrados en Matemáticas y Física" },
  { value: "29", label: "406 - Laboratorios de Ensayos de Materiales" },
  { value: "30", label: "407 - Posgrados en Materiales" },
  { value: "31", label: "408 - Laboratorio de Ensayos Hidráulicos" },
  { value: "32", label: "409 - Laboratorio de Hidráulica" },
  { value: "33", label: "411 - Laboratorios Ingeniería Eléctrica y Mecánica (Patios)" },
  { value: "34", label: "412 - Laboratorios Ingeniería Química" },
  { value: "35", label: "413 - Observatorio Astronómico" },
  { value: "36", label: "421 - Biología" },
  { value: "37", label: "425 - Instituto de Ciencias Naturales" },
  { value: "38", label: "426 - Instituto de Genética" },

  // Columna 3
  { value: "39", label: "431 - IPABM (antiguo IDAP)" },
  { value: "40", label: "433 - Almacén general e Imprenta" },
  { value: "41", label: "434 - IPABM" },
  { value: "42", label: "435 - Talleres de mantenimiento" },
  { value: "43", label: "436 - Transportes" },
  { value: "44", label: "437 - Centro de acopio de residuos sólidos" },
  { value: "45", label: "438 - Talleres y vestieres de mantenimiento" },
  { value: "46", label: "450 - Farmacia" },
  { value: "47", label: "451 - Química" },
  { value: "48", label: "452 - Posgrados Bioquímica y Carbones" },
  { value: "49", label: "453 - Guillermina Uribe Bone ( Aulas de Ingeniería )" },
  { value: "50", label: "454 - Edificio de Ciencia y Tecnología (CYT)" },
  { value: "51", label: "471 - Medicina" },
  { value: "52", label: "473 - Casa de animales" },
  { value: "53", label: "474 - Cafetería de Medicina" },
  { value: "54", label: "476 - Facultad de Ciencias" },
  { value: "55", label: "477 - PDSAV" },
  { value: "56", label: "480 - CEMU" },
  { value: "57", label: "481 - Facultad de Veterinaria" },

  { value: "58", label: "500 - Ciencias Agrarias" },
  { value: "59", label: "501 - Cirugía y clínica grandes animales" },
  { value: "60", label: "502 - Aulas de histopatología e inseminación" },
  { value: "61", label: "503 - Auditorio, anfiteatro y microbiología" }, // Corregido
  { value: "62", label: "504 - Patología aviar y URBAS" }, // Corregido
  { value: "63", label: "505 - Laboratorio de inseminación y corral" },
  { value: "64", label: "506 - Laboratorio patología y corral" },
  { value: "65", label: "507 - Clínica de pequeños animales" },
  { value: "66", label: "508 - Oficinas Facultad de Veterinaria" },
  { value: "67", label: "510 - Aulas y oficinas Facultad de Veterinaria" },
  { value: "68", label: "561 - Bloque Posgrados de Veterinaria" },
  { value: "69", label: "561A - Oficinas producción animal" },
  { value: "70", label: "561B - Posgrado reproducción animal" },
  { value: "71", label: "561C - Bioterio y establos" },
  { value: "72", label: "571 - Hemeroteca Nacional" },
  { value: "73", label: "606 - IICR" },
  { value: "74", label: "608 - Centro de Computo" },
  { value: "75", label: "610 - ICAC" },
  { value: "76", label: "615 - Laboratorio de Química" },
  { value: "77", label: "701 - Cine y Televisión" },
  { value: "78", label: "731 - Estadio Alfonso López" },
  { value: "79", label: "861 - Edificio Uriel Gutiérrez" },
  { value: "80", label: "862 - Unidad Camilo Torres (A, B, C)" },

  { value: "81", label: "921 - Hospital Universitario Nacional" },

 { value: "82", label: "Él Freud" },
 { value: "83", label: "La playita" },
 { value: "84", label: "Plaza Central (Che)" },
 { value: "85", label: "303 - Nuevo Espacio Para Las Artes (NEA)" },
 { value: "86", label: "El bunker / tienda universitaria" },
 { value: "87", label: "La perola" },
 { value: "88", label: "Portería Calle 53" },
 { value: "89", label: "Portería carrera 30" },
 { value: "90", label: "Portería de la capilla" },
 { value: "91", label: "Portería calle 26" },
 { value: "92", label: "Portería ICA" },
 { value: "93", label: "Portería Hemeroteca" },
 { value: "94", label: "Portería carrera 45" },
 { value: "95", label: "ICONTEC" },
 { value: "96", label: "Agustin Codazzi" },

];


export const categoryFound = [
  "TODAS",
  "Electrónica",
  "Accesorios personales",
  "Documentos",
  "Ropa y calzado",
  "Bolsos y mochilas",
  "Llaves y tarjetas",
  "Libros y papelería",
  "Artículos deportivos",
  "Juguetes y entretenimiento",
  "Salud y cuidado personal",
  "Otros",
];


export const locationOptions = [
  { value: "101 - Torre de Enfermería", label: "101 - Torre de Enfermería" },
  { value: "102 - Biblioteca Central Gabriel García Márquez (Central)", label: "102 - Biblioteca Central Gabriel García Márquez (Central)" },
  { value: "103 - Centro Polideportivo", label: "103 - Centro Polideportivo" },
  { value: "104 - Auditorio León de Greffi", label: "104 - Auditorio León de Greffi" },
  { value: "201 - Derecho", label: "201 - Derecho" },
  { value: "205 - Sociología (Ciencias Humanas)", label: "205 - Sociología (Ciencias Humanas)" },
  { value: "207 - Museo de Arquitectura Leopoldo Rother", label: "207 - Museo de Arquitectura Leopoldo Rother" },
  { value: "210 - Odontología", label: "210 - Odontología" },
  { value: "212 - Aulas de Ciencias Humanas", label: "212 - Aulas de Ciencias Humanas" },
  { value: "214 - Antonio Narino", label: "214 - Antonio Narino" },
  { value: "217 - Diseño Gráfico", label: "217 - Diseño Gráfico" },
  { value: "224 - Edificio Manuel Ancizar", label: "224 - Edificio Manuel Ancizar" },
  { value: "225 - Posgrados de Ciencias Humanas", label: "225 - Posgrados de Ciencias Humanas" },
  { value: "228 - Nuevo Edificio de Enfermería", label: "228 - Nuevo Edificio de Enfermería" },
  { value: "229 - Lenguas Extranjeras", label: "229 - Lenguas Extranjeras" },
  { value: "238 - Contaduria", label: "238 - Contaduria" },
  { value: "239 - Filosofía", label: "239 - Filosofía" },
  { value: "251 - Capilla", label: "251 - Capilla" },
  { value: "301 - Bellas Artes", label: "301 - Bellas Artes" },
  { value: "305 - Conservatorio de Música", label: "305 - Conservatorio de Música" },
  { value: "309 - Talleres y aulas de construcción", label: "309 - Talleres y aulas de construcción" },
  { value: "310 - Facultad de Ciencias Económicas", label: "310 - Facultad de Ciencias Económicas" },
  { value: "311 - Facultad de Ciencias Económicas Bloque II", label: "311 - Facultad de Ciencias Económicas Bloque II" },
  { value: "314 - SINDU", label: "314 - SINDU" },
  { value: "317 - Museo de Arte", label: "317 - Museo de Arte" },
  { value: "401 - Ingeniería Julio Garavito (El viejo)", label: "401 - Ingeniería Julio Garavito (El viejo)" },
  { value: "404 - Matemáticas y Física Y/o Takeuchi", label: "404 - Matemáticas y Física Y/o Takeuchi" },
  { value: "405 - Posgrados en Matemáticas y Física", label: "405 - Posgrados en Matemáticas y Física" },
  { value: "406 - Laboratorios de Ensayos de Materiales", label: "406 - Laboratorios de Ensayos de Materiales" },
  { value: "407 - Posgrados en Materiales", label: "407 - Posgrados en Materiales" },
  { value: "408 - Laboratorio de Ensayos Hidráulicos", label: "408 - Laboratorio de Ensayos Hidráulicos" },
  { value: "409 - Laboratorio de Hidráulica", label: "409 - Laboratorio de Hidráulica" },
  { value: "411 - Laboratorios Ingeniería Eléctrica y Mecánica (Patios)", label: "411 - Laboratorios Ingeniería Eléctrica y Mecánica (Patios)" },
  { value: "412 - Laboratorios Ingeniería Química", label: "412 - Laboratorios Ingeniería Química" },
  { value: "413 - Observatorio Astronómico", label: "413 - Observatorio Astronómico" },
  { value: "421 - Biología", label: "421 - Biología" },
  { value: "425 - Instituto de Ciencias Naturales", label: "425 - Instituto de Ciencias Naturales" },
  { value: "426 - Instituto de Genética", label: "426 - Instituto de Genética" },
  { value: "Él Freud", label: "Él Freud" },
  { value: "La playita", label: "La playita" },
  { value: "Plaza Central (Che)", label: "Plaza Central (Che)" },
  { value: "303 - Nuevo Espacio Para Las Artes (NEA)", label: "303 - Nuevo Espacio Para Las Artes (NEA)" },
  { value: "El bunker / tienda universitaria", label: "El bunker / tienda universitaria" },
  { value: "La perola", label: "La perola" },
  { value: "Portería Calle 53", label: "Portería Calle 53" },
  { value: "Portería carrera 30", label: "Portería carrera 30" },
  { value: "Portería de la capilla", label: "Portería de la capilla" },
  { value: "Portería calle 26", label: "Portería calle 26" },
  { value: "Portería ICA", label: "Portería ICA" },
  { value: "Portería Hemeroteca", label: "Portería Hemeroteca" },
  { value: "Portería carrera 45", label: "Portería carrera 45" },
  { value: "ICONTEC", label: "ICONTEC" },
  { value: "Agustin Codazzi", label: "Agustin Codazzi" },
];
