export const JWT_CONFIG = {
  ACCESS_TOKEN_SECRET: 'Jx#8vF@2LmQz!YpWz$7dTnM4KoXc',
  REFRESH_TOKEN_SECRET: 'yPq9%Vc#XgZr&AmWnT$3yLoK7TfD8',
  ACCESS_TOKEN_EXPIRES_IN: '10m',
  REFRESH_TOKEN_EXPIRES_IN: '30m',
};
